services:

  mongo:
    image: mongo:6.0.2
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: signature_extractor_db
    volumes:
      - ./mongo-data:/data/db
  nui:
    image: ghcr.io/nats-nui/nui:edge
    volumes:
      - ./db:/db
    ports:
      - "31312:31311"
  nats:
    image: nats
    volumes: 
      - "./nats:/data"
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    command: ["-js", "-sd", "/data"]